user1 = User.create(username: "kiki", zipcode: "90210")
user2 = User.create(username: "bobo", zipcode: "94109")
user3 = User.create(username: "zozo", zipcode: "94608")
user4 = User.create(username: "lala", zipcode: "94610")
user5 = User.create(username: "tim", zipcode: "94611")
user6 = User.create(username: "bingbong", zipcode: "94117")
user7 = User.create(username: "pickle", zipcode: "94588")
user8 = User.create(username: "albert", zipcode: "90505")
user9 = User.create(username: "aaron", zipcode: "90010")
user10 = User.create(username: "david", zipcode: "90005")

restaurant1 = Restaurant.create(name: "Mona Lisa Restaurant", zipcode: "94103", url: "https://monalisasf.com")
restaurant2 = Restaurant.create(name: "La Mar", zipcode: "94111", url: "https://lamarsf.com")
restaurant3 = Restaurant.create(name: "Sotto Mare", zipcode: "94133", url: "https://sottomaresf.com")
restaurant4 = Restaurant.create(name: "Benu", zipcode: "94105", url: "https://benusf.com")
restaurant5 = Restaurant.create(name: "Tony's Pizza", zipcode: "94133", url: "https://tonyspizzanapoletana.com")
restaurant6 = Restaurant.create(name: "Burma Superstar", zipcode: "94118", url: "https://burmasuperstar.com")
restaurant7 = Restaurant.create(name: "Ike's Sandwiches", zipcode: "94109", url: "https://loveandsandsandwiches.com")
restaurant8 = Restaurant.create(name: "Halal Guys", zipcode: "94102", url: "https://thehalalguys.com")
restaurant9 = Restaurant.create(name: "Golden Boy Pizza", zipcode: "94133", url: "https://goldenboypizza.com")
restaurant10 = Restaurant.create(name: "IHOP", zipcode: "94133", url: "https://ihop.com")

review1 = Review.create(user: user1, restaurant: restaurant10, rating: 5)
review2 = Review.create(user: user10, restaurant: restaurant1, rating: 3)
review3 = Review.create(user: user3, restaurant: restaurant5, rating: 1)
review4 = Review.create(user: user5, restaurant: restaurant1, rating: 4)
review5 = Review.create(user: user1, restaurant: restaurant8, rating: 2)
